### ISSUE TITLE
Integration with TravisCI: pip install fails with permission denied error

### ISSUE THREAD

**Issue by php-coder** [svenkreiss/html5validator#11]
In `Integration with TravisCI` chapter I see the example of `.travis.yml` that is using `pip install html5validator` command, but it fails with "permission denied" error. In this case we should use `--user` option: http://stackoverflow.com/questions/27036259/how-to-write-travis-yml-if-my-project-deps-on-python-and-nodejs

Probably, it also affects old-style builds, that don't use the docker infrastructure.

**Comment by svenkreiss** [comment]
The link you give to stackoverlfow seems specific to node js projects (and possibly other languages) where the `.travis.yml` file contains `language: node_js`. Is that what you have too?

If that is the problem, it would be nice to add a note to the readme that points out the `--user` option if the project language is not `language: python`.

**Comment by php-coder** [comment]
Yes, this is my case (I have `language: java`).

**Comment by svenkreiss** [comment]
@php-coder: I added a note to the section in the README file. Does that work for you?

Thanks for reporting this. I assume it is common that people use a different language than Python in their tests. This will help a lot of people.

**Comment by php-coder** [comment]
>I added a note to the section in the README file. Does that work for you?

Yes, thank you!

(But now I'm blocked by StackOverflowError...)
