### ISSUE TITLE
--ignore is broken after updating to 0.2.1

### ISSUE THREAD

**Issue by php-coder** [svenkreiss/html5validator#13]
After updating to 0.2.1 `--ignore` option gets ignored.

I'm invoking htmlvalidator with the following command: `html5validator --root src/main/webapp/WEB-INF/views --ignore 'Attribute “(th|sec|togglz|xmlns):[a-z]+” not allowed' 'Attribute “(th|sec|togglz):[a-z]+” is not serializable' 'Attribute with the local name “xmlns:[a-z]+” is not serializable' --show-warnings`

**Comment by svenkreiss** [comment]
There is a breaking API change: what was --ignore is now --ignore-re.

**Comment by php-coder** [comment]
Ah, I see now. Thank you and I'm sorry.

**Comment by svenkreiss** [comment]
no worries. Better one bug report more than a bug that goes unreported.
