### ISSUE TITLE
Silent error under Cygwin: files passed to v.Nu with a unix-path are ignored

### ISSUE THREAD

**Issue by Lucas-C** [svenkreiss/html5validator#27]
Hello.

This is an issue very similar to #20.

I have a PR coming to fix it.

**Comment by Lucas-C** [comment]
Thanks for the merge !
When do you plan to do a release next ?

**Comment by svenkreiss** [comment]
Just did. Let me know if you notice any problems with it. Unfortunately, I don't have a Cygwin environment to test it.

**Comment by Lucas-C** [comment]
It works perfectly, thanks !
