### ISSUE TITLE
Is it possible to use html5validator without writing generated HTML files on disk (or in tmpfs)?

### ISSUE THREAD

**Issue by int-ua** [svenkreiss/html5validator#30]
AFAIU, `localcrawl` can't validate HTML on the fly, it just writes files and I can use `wget` as well for this. But all I want to do is to check a list of URLs on localhost, do I absolutely have to designate a filename for them with some wrapper script?

**Comment by svenkreiss** [comment]
Yes, you can use `wget` if your files don't contain any Javascript.

At the moment, you need temporary files in an intermediate step.

**Comment by int-ua** [comment]
FYI: I ended up using this package for launching the validation server and using https://github.com/peterbe/django-html-validator with `HTMLVALIDATOR_VNU_URL = 'http://localhost:8888/'`
