### ISSUE TITLE
X-UA-Compatible not recognized as valid

### ISSUE THREAD

**Issue by eksperimental** [svenkreiss/html5validator#4]
Hi, I am working on a website, and I realized, this app doesn' t recognize
`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`
I get:
> error: Bad value “X-UA-Compatible” for attribute “http-equiv” on element “meta”.

but If validate the same page in:
https://html5.validator.nu/
it passes without warnings, which makes me assume that this project is running on an older version of the validator. if so, could it be possible to update it and release a new pip package.
I' m trying to integrate elixir-lang.org (https://github.com/elixir-lang/elixir-lang.github.com/) on travis, and I won' t be able to until this little issue is solve.
let me know if you need more input from my side,
thanks a lot, I use your project a lot to validate this website (but for the time being just locally)
cheers

**Comment by Supuhstar** [comment]
+1 I've had this problem for a while. I hate seeing my webpages invalidated simply because I want IE to work as I intend.

**Comment by svenkreiss** [comment]
Hi @eksperimental. Sorry I was away for a few days.

Do you mind if I add a copy of the HTML of your front page to the unit tests? I have html5validator running with a new version.
And just a heads up: it does not like the `,chrome=1` you have for `X-UA-Compatible` now.

Waiting for your ok before committing. If not ok, no problem at all.

@Supuhstar: always just let me know about these problems or send PR.

**Comment by eksperimental** [comment]
Hi svenkreiss,
Well, it's not my website, but a project I usually contribute to..
Yes, go for it, as I don't see anything wrong with the license from our side,
https://github.com/elixir-lang/elixir-lang.github.com/#license
but the HTML itself, as stated in the link above, is GPL v2
I don't know if there is any incompatibility with MIT.

yes, I know ",chorme" will not work, but since because still had this issue with any "X-UA-Compatible", and I was running another validator that had the othe issues,
I decided to write a filter in bash to bypass all these errors, 
You can have a look at it here,
https://github.com/elixir-lang/elixir-lang.github.com/pull/485/files?diff=unified
I will create a repo in github and release it soon,
So i'm sure it will help to spread your project as well as more people will be able to finetune the errors given by html5validator, and be able include it in their CI project.

**Comment by eksperimental** [comment]
the original html is this theme called origin, http://alienwp.com/themes/origin/
which can be downloaded here: http://wordpress.org/themes/download/origin.0.5.6.zip

**Comment by svenkreiss** [comment]
The latest version has a `--ignore` flag that takes regular expressions to ignore certain errors specified by the user. Should be helpful in case you need to keep the `chrome=1` in the `X-UA-Compatible`.
