### ISSUE TITLE
Undocumented Validator API breaking changes in v0.2.10

### ISSUE THREAD

**Issue by Lucas-C** [svenkreiss/html5validator#40]
Pypi latest version of this package is v0.2.10, but there is no matching tag in GitHub,
nor a mention of it in the README Changelog.

Sadly this version broke my [`pre-commit` hook](https://github.com/Lucas-C/pre-commit-hooks-java) using it :(
Indeed, `Validator.validate` does not accept anymore the `errors_only` nor `stack_size` parameter.

**Comment by svenkreiss** [comment]
Whoops. Didn't know anyone relies on the internal API.

Some changes were necessary to support new options in `vnu.jar`. It is actually more general now but the interface is not that pretty.
Can you check the changes proposed in #41 and provide comments if you have any?

**Comment by Lucas-C** [comment]
No problem. I switched my lib to the new API: https://github.com/Lucas-C/pre-commit-hooks-java/releases/tag/1.3.7
The changes seem legitimate, I don't have any thing to add.

**Comment by svenkreiss** [comment]
@Lucas-C just a heads up that #41 changed the internal API again. This is not on PyPI yet but will be soon.

**Comment by Lucas-C** [comment]
Thank you very much

**Comment by Lucas-C** [comment]
Just for documentation purpose, some more API changes were also made in https://github.com/svenkreiss/html5validator/commit/a42c732150fef79a4f5444bfc1920c06ea661b16
