### ISSUE TITLE
Expose --Werror vnu option

### ISSUE THREAD

**Issue by php-coder** [svenkreiss/html5validator#43]
In the PR #39 you exposed a couple options and also updated vnu.jar to a new version that has useful  `--Werror` option. Could it be exposed to html5validator?

I'm surprised that it's not enabled by default...

**Comment by svenkreiss** [comment]
The return code of html5validator is calculated differently from `vnu.jar`. We have a `--show-warnings` option which also affects the return code. Is that what you are looking for?

**Comment by php-coder** [comment]
> We have a --show-warnings option which also affects the return code.

Does it mean that html5validator will return 1 when only warnings encountered?

**Comment by svenkreiss** [comment]
Yes.

... and I realize there is no unit test for that. There should be.
