### ISSUE TITLE
Validate CSS

### ISSUE THREAD

**Issue by andricicezar** [svenkreiss/html5validator#47]
Can I validate CSS with this tool? I would like to validate all html and css files. From the Nu HTML Checker's Documentation I see that I should be able to do that with the flag `--also-check-css`, but html5validator doesn't seem to support it. Any other way? Can I use directly HTML Checker?

**Comment by sideshowbarker** [comment]
As the upstream maintainer, I’ll step in here and note that I’ve not yet done a stable release of the HTML checker that has the CSS support. But I plan to do that within the next 2 weeks at most. So I assume that html5validator will be able to integrate that some time soon after I release it.

**Comment by Croydon** [comment]
Can this be moved forward?

**Comment by Croydon** [comment]
@sideshowbarker @svenkreiss Are there still any blockers for this?

**Comment by svenkreiss** [comment]
I'll look into releasing a new version. Thanks for the reminder.
