### ISSUE TITLE
The checker requires a java thread stack size of at least 512k

### ISSUE THREAD

**Issue by jorgesumle** [svenkreiss/html5validator#49]
```~/Repositorio/libremanuals.github.io [master|✚ 1] 
13:48 $ html5validator --root .
ERROR:html5validator.validator:StackOverflowError while evaluating HTML schema.
The checker requires a java thread stack size of at least 512k.
Consider invoking java with the -Xss option. For example:

  java -Xss512k -jar ~/vnu.jar FILE.html
```

Using Uruk GNU/Linux 2.0 (32bit) on a Lenovo X60. Is there a way I can invoke Java that way from html5validator and solve my issue?

**Comment by svenkreiss** [comment]
Can you try the `-l`, `-ll` or `-lll` options? Does that work for you?

**Comment by jorgesumle** [comment]
> Can you try the -l, -ll or -lll options? Does that work for you?

Yes, that works. What about adding an error message that suggest using that options when such an error occurs?
