### ISSUE TITLE
error: CSS: Parse Error

### ISSUE THREAD

**Issue by raybogman** [svenkreiss/html5validator#54]
Hi, I keep getting the message "93.11-93.11: error: CSS: Parse Error"
I now this relates to html line 93 postion 11.
that line looks like: 

  .highlight .hll{background-color:#373b41}

view-source:https://tedxamstelveen.com/

my html5 looks like:

  - html5validator --root _site/ --log DEBUG --ignore-re '⚡' 'custom-element' 'amp-boilerplate' 'amp-custom' 'on'

is there a option to get more info on the "CSS: Parse Error"?

or would there be a new option to disable css validation tmp

thanx.

**Comment by jwhite1st** [comment]
What does your output look like for CSS: Parse Error?
and if you don't want CSS to be checked then you can use ```--match *.html```
