### ISSUE TITLE
Add a Github Action please?

### ISSUE THREAD

**Issue by jasikpark** [svenkreiss/html5validator#67]

**Comment by svenkreiss** [comment]
I am not familiar with Github Actions myself yet, but @Cyb3r-Jak3 seems to have done something in that direction: https://github.com/marketplace/actions/html5-validator
Is that what you are looking for?

**Comment by jasikpark** [comment]
Probably, thanks for your help!

--  
Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz
