### ISSUE TITLE
"Found files to validate: 1"

### ISSUE THREAD

**Issue by szepeviktor** [svenkreiss/html5validator#7]
Good morning!

Is `Found files to validate: 1` the expected output?
Does it mean that it is valid??
https://travis-ci.org/szepeviktor/ip-info/builds/82826416#L95

Would it be possible to include this in the readme?

Thank you!

**Comment by szepeviktor** [comment]
I hope in the next release it'll work:
https://travis-ci.org/szepeviktor/ip-info/builds/84567981

**Comment by svenkreiss** [comment]
That version was not released yet. It is now.

Use something like `--log INFO` to see the info messages that include a list of the files.
Let me know if you see any problems.

**Comment by szepeviktor** [comment]
`All good.`
https://travis-ci.org/szepeviktor/ip-info/builds/84580215
Thanks.
