### ISSUE TITLE
Can we get a new pip release please?

### ISSUE THREAD

**Issue by mhansen** [svenkreiss/html5validator#71]
I'd particularly like one that includes 67ecbc01a66ed68ce059bf69a732f67e62a45a7e

**Comment by bittner** [comment]
True. This will likely provide a more readable, more usable validation output to everyone.

**Comment by Cyb3r-Jak3** [comment]
@svenkreiss Bump on this. If you want I can open a PR for auto-deployment to PyPi on a new tag.

**Comment by svenkreiss** [comment]
v0.4.0 is finally out 🍾

**Comment by mhansen** [comment]
Thank you Sven; appreciate this :-)

**Comment by bittner** [comment]
Thank you, Sven! :100: 

Now also available as an updated [Docker image](https://hub.docker.com/r/painless/html5validator/). :wales:
