### ISSUE TITLE
Consider using --stdout option to vnu.jar

### ISSUE THREAD

**Issue by mhansen** [svenkreiss/html5validator#72]
Hi there, the maintainer of https://github.com/validator/validator, which this depends on, just added an option to the validator to output the HTML warnings & HTML errors to stdout, while leaving stderr free for exceptional cases (exceptions, error messages that are unrelated to the HTML).

https://github.com/validator/validator/commit/1ce0b83873c2da0c374373764efec2b1a5532e4e

You might consider switching to setting `--stdout`, and reading from the stdout stream rather than the stderr stream. This would save you having to filter out errors from the stream like `Picked up _JAVA_OPTIONS:` here: https://github.com/svenkreiss/html5validator/blob/master/html5validator/validator.py#L17.

**Comment by bittner** [comment]
@mhansen Could you turn your suggestion into an acitonable PR, please? This will make it more likely that your feature suggestion comes true.

**Comment by svenkreiss** [comment]
No, filing an issue to let us know about this nice new addition to the validator is valid. No PR necessary. Thank you @mhansen .

**Comment by mhansen** [comment]
I'm happy to try my hand at a pull request, just wanted to check with you
first if this would be desired.
