### ISSUE TITLE
Documentation of config file

### ISSUE THREAD

**Issue by sww1235** [svenkreiss/html5validator#85]
Can you please provide documentation on the `CONFIG FILE` option in the `README.MD` file? 

Ideally, there would be a list of options that can be placed in the config file, along with the correct syntax and file format for the config file.

If this config file is specifically for validator.nu, and there is good documentation provided by that project, then provide a link to said documentation.

if the `CONFIG FILE` option is deprecated or non-functional, then provide a warning to that effect.

Thank you

**Comment by Cyb3r-Jak3** [comment]
Example config files can be found in the [tests](https://github.com/svenkreiss/html5validator/tree/main/html5validator/tests/config_files).
