### ISSUE TITLE
AttributeError: module 'os' has no attribute 'errno'

### ISSUE THREAD

**Issue by jdoe0000000** [svenkreiss/html5validator#86]
`os.errno` [has been removed since Python 3.7](https://bugs.python.org/issue33666), but it's still being used in `validator.py`:

https://github.com/svenkreiss/html5validator/blob/81fbe36827a3dd0b7100cd4787dac1b167e4a32f/html5validator/validator.py#L154

This causes the validator to crash with the following error message instead of notifying the user that Java is missing.

```
AttributeError: module 'os' has no attribute 'errno'
```

**Comment by fetzerch** [comment]
Is there a chance to get a new release with this fix included? Python 3.6 is EOL and a new release would make it usable on newer Python versions.
